#!/bin/bash

set -e


DCMAKE_BUILD_TYPE=RelWithDebInfo


# check if current directory is compiler
if [ ! "$(basename $PWD)" = "compiler" ]; then
  echo "script not run in compiler directory"
  exit 1
fi


# if deps folder exists, ask whether user wants to reinstall deps. if Y (default), delete; if n, exit
if [ -d "deps" ]; then
  read -p "Directory deps exists. Do you want to reinstall dependencies? (Y/n) " -n 1 -r
  echo
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    rm -rf deps
    echo "Deleted deps directory"
  else
    echo "Exiting"
    exit 0
  fi
fi

echo "asdasdasd"


# create deps directory
mkdir -p deps
cd deps


# clone CIRCT and build LLVM/MLIR
git clone https://github.com/llvm/circt.git; cd circt
git submodule init; git submodule update
mkdir llvm/build; cd llvm/build
cmake -G Ninja ../llvm \
    -DLLVM_ENABLE_PROJECTS="mlir" \
    -DLLVM_TARGETS_TO_BUILD="host" \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DCMAKE_BUILD_TYPE=$DCMAKE_BUILD_TYPE \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
ninja # you might have to limit cores with -j if you get random failures
ninja check-mlir


# Build CIRCT
cd ../../
mkdir build; cd build
cmake -G Ninja .. \
    -DMLIR_DIR="../llvm/build/lib/cmake/mlir" \
    -DLLVM_DIR="../llvm/build/lib/cmake/llvm" \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DCMAKE_BUILD_TYPE=$DCMAKE_BUILD_TYPE \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
ninja
ninja check-circt
ninja check-circt-integration


# Build Torch-MLIR
cd ../../
git clone https://github.com/llvm/torch-mlir; cd torch-mlir
git submodule update --init --progress
cmake -GNinja -Bbuild \
  -DCMAKE_BUILD_TYPE=Release \
  -DPython3_FIND_VIRTUALENV=ONLY \
  -DMLIR_DIR="../circt/llvm/build/lib/cmake/mlir/" \
  -DLLVM_DIR="../circt/llvm/build/lib/cmake/llvm/" \
  -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
  -DLLVM_TARGETS_TO_BUILD=host \
  .
cmake --build build --target tools/torch-mlir/all


# Create enable script that adds CIRCT and Torch-MLIR binaries to PATH
cd ../../
echo "export PATH=$PWD/deps/circt/build/bin:$PWD/deps/torch-mlir/build/bin:\$PATH" > enable
echo "Dependencies installed. Run 'source enable' to add CIRCT and Torch-MLIR binaries to PATH."
exit 0
